FROM golang:1.22.2

WORKDIR /datanode1

COPY go.mod go.sum ./

RUN go mod download

COPY . .

RUN go build -o datanode1 ./datanode1
RUN go get github.com/FranciscoMunozP/Lab4Proto

EXPOSE 50053
RUN go build -o datanode1_bin .

ENTRYPOINT ["./datanode1_bin"]