FROM golang:1.22.2

WORKDIR /datanode2

COPY go.mod go.sum ./

RUN go mod download

COPY . .

RUN go build -o datanode2 ./datanode2
RUN go get github.com/FranciscoMunozP/Lab4Proto

EXPOSE 50053
RUN go build -o datanode2_bin .

ENTRYPOINT ["./datanode2_bin"]