FROM golang:1.22.2

WORKDIR /Bank

COPY go.mod go.sum ./

RUN go mod download

COPY Bank/banco.go ./

RUN go build -o  ./banco
RUN go get github.com/FranciscoMunozP/Lab4Proto

EXPOSE 50053
EXPOSE 5672
RUN go build -o banco_bin .

ENTRYPOINT ["./banco_bin"]