FROM golang:1.22.2

WORKDIR /namenode

COPY go.mod go.sum ./

RUN go mod download

COPY . .

RUN go build -o  ./name
RUN go get github.com/FranciscoMunozP/Lab4Proto

EXPOSE 50053
RUN go build -o name_bin .

ENTRYPOINT ["./name_bin"]
