FROM golang:1.22.2

WORKDIR /datanode3

COPY go.mod go.sum ./

RUN go mod download

COPY . .

RUN go build -o datanode3 ./datanode3
RUN go get github.com/FranciscoMunozP/Lab4Proto

EXPOSE 50053
RUN go build -o datanode3_bin .

ENTRYPOINT ["./datanode3_bin"]
